export const mockFlights = [
    {
      id: "AA1234",
      airline: "American Airlines",
      logo: "/logos/american.svg",
      arrival: {
        airport: "Dublin Airport (DUB)",
        date: "8 May, Thursday",
        time: "11:15 AM",
        terminal: "Terminal 2",
        day: "+1",
      },
      departure: {
        airport: "John F Kennedy International (JFK)",
        date: "7 May, Wednesday",
        time: "7:30 PM",
        terminal: "Terminal 4",
      },
      duration: "10hr 45min",
      price: {
        current: 60454,
        original: 62753,
        currency: "Tk",
      },
      promo: "SAVEONUSD",
      refundable: false,
      cabinClass: "Economy",
      route: "JFK - DUB",
      seats: 23,
      baggage: "7kg hand baggage",
      stops: {
        airport: "London Heathrow (LHR)",
        count: 1,
        duration: "2hr 5min",
      },
      score: 8.7,
      emissions: "Low CO2 emissions",
    },
    {
      id: "EK203",
      airline: "Emirates",
      logo: "/logos/emirates.svg",
      arrival: {
        airport: "Dublin Airport (DUB)",
        date: "8 May, Thursday",
        time: "10:45 AM",
        terminal: "Terminal 2",
      },
      departure: {
        airport: "John F Kennedy International (JFK)",
        date: "7 May, Wednesday",
        time: "11:55 PM",
        terminal: "Terminal 4",
      },
      duration: "9hr 50min",
      price: {
        current: 61404,
        original: 63000,
        currency: "Tk",
      },
      promo: "FIRST50",
      refundable: true,
      cabinClass: "Economy",
      route: "JFK - DUB",
      seats: 15,
      baggage: "10kg hand baggage",
      stops: {
        airport: "Dubai International (DXB)",
        count: 1,
        duration: "3hr 20min",
      },
      score: 9.1,
      emissions: "Average CO2 emissions",
    },
    {
      id: "QR702",
      airline: "Qatar Airways",
      logo: "/logos/qatar.svg",
      arrival: {
        airport: "Dublin Airport (DUB)",
        date: "8 May, Thursday",
        time: "8:30 AM",
        terminal: "Terminal 2",
        day: "+1",
      },
      departure: {
        airport: "John F Kennedy International (JFK)",
        date: "7 May, Wednesday",
        time: "10:20 PM",
        terminal: "Terminal 4",
      },
      duration: "11hr 10min",
      price: {
        current: 117793,
        original: 120000,
        currency: "Tk",
      },
      promo: null,
      refundable: true,
      cabinClass: "Economy",
      route: "JFK - DUB",
      seats: 8,
      baggage: "10kg hand baggage",
      stops: {
        airport: "Doha Hamad (DOH)",
        count: 1,
        duration: "2hr 30min",
      },
      score: 9.5,
      emissions: "Low CO2 emissions",
    },
    {
      id: "BA178",
      airline: "British Airways",
      logo: "/logos/british.svg",
      arrival: {
        airport: "Dublin Airport (DUB)",
        date: "8 May, Thursday",
        time: "8:50 AM",
        terminal: "Terminal 2",
      },
      departure: {
        airport: "John F Kennedy International (JFK)",
        date: "7 May, Wednesday",
        time: "9:15 PM",
        terminal: "Terminal 7",
      },
      duration: "10hr 30min",
      price: {
        current: 122245,
        original: 125000,
        currency: "Tk",
      },
      promo: null,
      refundable: false,
      cabinClass: "Economy",
      route: "JFK - DUB",
      seats: 5,
      baggage: "7kg hand baggage",
      stops: {
        airport: "London Heathrow (LHR)",
        count: 1,
        duration: "1hr 30min",
      },
      score: 8.8,
      emissions: "Average CO2 emissions",
    },
    {
      id: "TK196",
      airline: "Turkish Airlines",
      logo: "/logos/turkish.svg",
      arrival: {
        airport: "Dublin Airport (DUB)",
        date: "8 May, Thursday",
        time: "8:25 AM",
        terminal: "Terminal 1",
        day: "+1",
      },
      departure: {
        airport: "John F Kennedy International (JFK)",
        date: "7 May, Wednesday",
        time: "11:35 PM",
        terminal: "Terminal 1",
      },
      duration: "11hr 50min",
      price: {
        current: 93850,
        original: 98000,
        currency: "Tk",
      },
      promo: "SPRING25",
      refundable: true,
      cabinClass: "First Class",
      route: "JFK - DUB",
      seats: 12,
      baggage: "8kg hand baggage",
      stops: {
        airport: "Istanbul (IST)",
        count: 1,
        duration: "2hr 45min",
      },
      score: 8.9,
      emissions: "Low CO2 emissions",
    },
    {
      id: "DL405",
      airline: "Delta Airlines",
      logo: "/logos/delta.svg",
      arrival: {
        airport: "Dublin Airport (DUB)",
        date: "8 May, Thursday",
        time: "11:05 AM",
      },
      departure: {
        airport: "John F Kennedy International (JFK)",
        date: "7 May, Wednesday",
        time: "9:00 PM",
      },
      duration: "7hr 05min",
      price: {
        current: 83397,
        original: 85000,
        currency: "Tk",
      },
      promo: null,
      refundable: false,
      cabinClass: "Business",
      route: "JFK - DUB",
      seats: 2,
      baggage: "7kg hand baggage",
      stops: {
        count: 0,
      },
      score: 9.3,
      emissions: "Low CO2 emissions",
    },
  ];
  
  export const timeFilterOptions = [
    {
      id: "morning-dep",
      label: "Morning",
      time: "05:00 - 11:59",
      type: "departure",
    },
    {
      id: "afternoon-dep",
      label: "Afternoon",
      time: "12:00 - 17:59",
      type: "departure",
    },
    {
      id: "evening-dep",
      label: "Evening",
      time: "18:00 - 22:59",
      type: "departure",
    },
    { id: "night-dep", label: "Night", time: "23:00 - 04:59", type: "departure" },
    {
      id: "morning-arr",
      label: "Morning",
      time: "05:00 - 11:59",
      type: "arrival",
    },
    {
      id: "afternoon-arr",
      label: "Afternoon",
      time: "12:00 - 17:59",
      type: "arrival",
    },
    {
      id: "evening-arr",
      label: "Evening",
      time: "18:00 - 22:59",
      type: "arrival",
    },
    { id: "night-arr", label: "Night", time: "23:00 - 04:59", type: "arrival" },
  ];